cino:
  frame:
    type: awt
    title: demo
    doublebuffer: true
    vsync: false
    fullscreen: false
    fps: 60
    flexible: true
    hidemouse: true
    flexmode: 0
    screen:
      width: 1920
      height: 1080
  debug.enable: true
  storage.location: ./
  layer.maxlayer: 128