cino:
  frame:
    type: awt
    title: demo
    doublebuffer: true
    vsync: false
    fullscreen: false
    fps: 60
    flexible: false
    hidemouse: true
    flexmode: 0
    screen:
      width: 800
      height: 600
  debug.enable: true
  storage.location: ./
  layer.maxlayer: 128